export const destinationData = [
  { city: "Paris", country: "France", region: "Europe", popularity_score: 95 },
  {
    city: "Berlin",
    country: "Germany",
    region: "Europe",
    popularity_score: 88,
  },
  { city: "Rome", country: "Italy", region: "Europe", popularity_score: 90 },
  {
    city: "Barcelona",
    country: "Spain",
    region: "Europe",
    popularity_score: 92,
  },
  {
    city: "Amsterdam",
    country: "Netherlands",
    region: "Europe",
    popularity_score: 89,
  },
  {
    city: "London",
    country: "United Kingdom",
    region: "Europe",
    popularity_score: 96,
  },
  {
    city: "Lisbon",
    country: "Portugal",
    region: "Europe",
    popularity_score: 85,
  },
  {
    city: "Prague",
    country: "Czech Republic",
    region: "Europe",
    popularity_score: 87,
  },
  {
    city: "Vienna",
    country: "Austria",
    region: "Europe",
    popularity_score: 91,
  },
  {
    city: "Zurich",
    country: "Switzerland",
    region: "Europe",
    popularity_score: 86,
  },

  {
    city: "New York",
    country: "USA",
    region: "North America",
    popularity_score: 97,
  },
  {
    city: "Los Angeles",
    country: "USA",
    region: "North America",
    popularity_score: 93,
  },
  {
    city: "Chicago",
    country: "USA",
    region: "North America",
    popularity_score: 89,
  },
  {
    city: "Miami",
    country: "USA",
    region: "North America",
    popularity_score: 91,
  },
  {
    city: "San Francisco",
    country: "USA",
    region: "North America",
    popularity_score: 95,
  },
  {
    city: "Toronto",
    country: "Canada",
    region: "North America",
    popularity_score: 90,
  },
  {
    city: "Vancouver",
    country: "Canada",
    region: "North America",
    popularity_score: 88,
  },
  {
    city: "Mexico City",
    country: "Mexico",
    region: "North America",
    popularity_score: 84,
  },
  {
    city: "Cancun",
    country: "Mexico",
    region: "North America",
    popularity_score: 87,
  },
  {
    city: "Montreal",
    country: "Canada",
    region: "North America",
    popularity_score: 85,
  },

  { city: "Tokyo", country: "Japan", region: "Asia", popularity_score: 96 },
  { city: "Osaka", country: "Japan", region: "Asia", popularity_score: 90 },
  { city: "Kyoto", country: "Japan", region: "Asia", popularity_score: 94 },
  {
    city: "Seoul",
    country: "South Korea",
    region: "Asia",
    popularity_score: 93,
  },
  {
    city: "Bangkok",
    country: "Thailand",
    region: "Asia",
    popularity_score: 91,
  },
  {
    city: "Singapore",
    country: "Singapore",
    region: "Asia",
    popularity_score: 95,
  },
  { city: "Hong Kong", country: "China", region: "Asia", popularity_score: 92 },
  { city: "Taipei", country: "Taiwan", region: "Asia", popularity_score: 89 },
  {
    city: "Kuala Lumpur",
    country: "Malaysia",
    region: "Asia",
    popularity_score: 87,
  },
  { city: "Beijing", country: "China", region: "Asia", popularity_score: 88 },

  {
    city: "Sydney",
    country: "Australia",
    region: "Oceania",
    popularity_score: 95,
  },
  {
    city: "Melbourne",
    country: "Australia",
    region: "Oceania",
    popularity_score: 93,
  },
  {
    city: "Brisbane",
    country: "Australia",
    region: "Oceania",
    popularity_score: 88,
  },
  {
    city: "Auckland",
    country: "New Zealand",
    region: "Oceania",
    popularity_score: 90,
  },
  {
    city: "Wellington",
    country: "New Zealand",
    region: "Oceania",
    popularity_score: 86,
  },
  { city: "Fiji", country: "Fiji", region: "Oceania", popularity_score: 84 },
  {
    city: "Tahiti",
    country: "French Polynesia",
    region: "Oceania",
    popularity_score: 83,
  },
  {
    city: "Perth",
    country: "Australia",
    region: "Oceania",
    popularity_score: 85,
  },
  {
    city: "Christchurch",
    country: "New Zealand",
    region: "Oceania",
    popularity_score: 82,
  },
  {
    city: "Gold Coast",
    country: "Australia",
    region: "Oceania",
    popularity_score: 89,
  },

  {
    city: "Rio de Janeiro",
    country: "Brazil",
    region: "South America",
    popularity_score: 92,
  },
  {
    city: "São Paulo",
    country: "Brazil",
    region: "South America",
    popularity_score: 90,
  },
  {
    city: "Buenos Aires",
    country: "Argentina",
    region: "South America",
    popularity_score: 91,
  },
  {
    city: "Lima",
    country: "Peru",
    region: "South America",
    popularity_score: 86,
  },
  {
    city: "Bogotá",
    country: "Colombia",
    region: "South America",
    popularity_score: 85,
  },
  {
    city: "Santiago",
    country: "Chile",
    region: "South America",
    popularity_score: 87,
  },
  {
    city: "Quito",
    country: "Ecuador",
    region: "South America",
    popularity_score: 83,
  },
  {
    city: "Cusco",
    country: "Peru",
    region: "South America",
    popularity_score: 88,
  },
  {
    city: "Montevideo",
    country: "Uruguay",
    region: "South America",
    popularity_score: 82,
  },
  {
    city: "Cartagena",
    country: "Colombia",
    region: "South America",
    popularity_score: 89,
  },

  {
    city: "Cape Town",
    country: "South Africa",
    region: "Africa",
    popularity_score: 91,
  },
  {
    city: "Johannesburg",
    country: "South Africa",
    region: "Africa",
    popularity_score: 87,
  },
  { city: "Nairobi", country: "Kenya", region: "Africa", popularity_score: 85 },
  {
    city: "Marrakesh",
    country: "Morocco",
    region: "Africa",
    popularity_score: 88,
  },
  { city: "Cairo", country: "Egypt", region: "Africa", popularity_score: 89 },
  {
    city: "Casablanca",
    country: "Morocco",
    region: "Africa",
    popularity_score: 86,
  },
  { city: "Accra", country: "Ghana", region: "Africa", popularity_score: 82 },
  { city: "Lagos", country: "Nigeria", region: "Africa", popularity_score: 83 },
  {
    city: "Zanzibar",
    country: "Tanzania",
    region: "Africa",
    popularity_score: 84,
  },
  {
    city: "Addis Ababa",
    country: "Ethiopia",
    region: "Africa",
    popularity_score: 80,
  },

  {
    city: "Reykjavik",
    country: "Iceland",
    region: "Europe",
    popularity_score: 85,
  },
  {
    city: "Helsinki",
    country: "Finland",
    region: "Europe",
    popularity_score: 86,
  },
  {
    city: "Stockholm",
    country: "Sweden",
    region: "Europe",
    popularity_score: 89,
  },
  { city: "Oslo", country: "Norway", region: "Europe", popularity_score: 88 },
  {
    city: "Copenhagen",
    country: "Denmark",
    region: "Europe",
    popularity_score: 90,
  },
  {
    city: "Tallinn",
    country: "Estonia",
    region: "Europe",
    popularity_score: 83,
  },
  { city: "Riga", country: "Latvia", region: "Europe", popularity_score: 82 },
  { city: "Warsaw", country: "Poland", region: "Europe", popularity_score: 85 },
  {
    city: "Budapest",
    country: "Hungary",
    region: "Europe",
    popularity_score: 91,
  },
  {
    city: "Dubrovnik",
    country: "Croatia",
    region: "Europe",
    popularity_score: 90,
  },
];
